### ISSUE TITLE
Reloading Settings page creates error and displayis nothing

### ISSUE THREAD

**Issue by chutko** [tenders-exposed/elvis-ember#334]
if i go directly to http://localhost:4200/account/settings, there is nothing but a dark background.
the only way to come there and see the content is by clicking the settings link in the navbar. 

also, when i edit the template, the page refreshes and there is no content just a dark background. it works normally on production though: http://tenders.exposed/account/settings

console output: 
```
Error while processing route: account.settings.index Assertion Failed: Attempting to inject an unknown injection: 'controller:application' Error: Assertion Failed: Attempting to inject an unknown injection: 'controller:application'
    at assert (http://localhost:4200/assets/vendor.js:28900:15)
    at Registry.validateInjections (http://localhost:4200/assets/vendor.js:25709:66)
    at FactoryManager.create (http://localhost:4200/assets/vendor.js:25320:35)
    at Proxy.create (http://localhost:4200/assets/vendor.js:24979:20)
    at instantiateFactory (http://localhost:4200/assets/vendor.js:25054:57)
    at lookup (http://localhost:4200/assets/vendor.js:25013:12)
    at Container.lookup (http://localhost:4200/assets/vendor.js:24878:14)
    at Class.lookup (http://localhost:4200/assets/vendor.js:52900:33)
    at Class.<anonymous> (http://localhost:4200/assets/vendor.js:46697:30)
    at ComputedPropertyPrototype.get (http://localhost:4200/assets/vendor.js:41004:28)
logError @ vendor.js:48866
vendor.js:41723 Error: Assertion Failed: Attempting to inject an unknown injection: 'controller:application'
    at assert (vendor.js:28900)
    at Registry.validateInjections (vendor.js:25709)
    at FactoryManager.create (vendor.js:25320)
    at Proxy.create (vendor.js:24979)
    at instantiateFactory (vendor.js:25054)
    at lookup (vendor.js:25013)
    at Container.lookup (vendor.js:24878)
    at Class.lookup (vendor.js:52900)
    at Class.<anonymous> (vendor.js:46697)
    at ComputedPropertyPrototype.get (vendor.js:41004)

```

**Comment by zufanka** [comment]
Still an issue???
